# Generated by Django 4.2.16 on 2025-05-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_savingproducts_savingoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='fin_prdt_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.savingproducts'),
        ),
    ]
